### ISSUE TITLE
[d487a5d8d7] Unable to save resume file: Too many open files

### ISSUE THREAD

**Issue by Coeur** [transmission/transmission#3028]
![Capture d’écran 2022-04-30 à 15 51 18](https://user-images.githubusercontent.com/839992/166097120-aa4c7b14-842c-42ec-91d3-c03b5943fab5.png)

This issue never happened before, but it's re-occurring even after rebooting the Mac, after a few minutes.
So possibly, it was caused by a recent commit. Screenshot from d487a5d8d738ccfa055560642b2c34286f87d826

[edit]
Haven't reproduced for 1 hour now. So maybe it was caused by some other process, like SourceTree? I was indeed cloning some big repo today (https://github.com/torvalds/linux).

**Comment by Coeur** [comment]
Fixed in #3036

**Comment by chaseholden** [comment]
This issue is still common in T 4.0.2 on macOS client - macOS 13.3 and 13.4 Ventura - M1 Ultra ARM64 - please reopen!
