### ISSUE TITLE
macOS Message Log flooded with tr-udp warnings

### ISSUE THREAD

**Issue by GaryElshaw** [transmission/transmission#4406]
### What is the issue?

Lots and lots of the below.

2022-12-19 11:07:46 +0000 tr-udp.cc:383 [Warning] tr-udp.cc:383: Couldn't send to 2804:41e0:fd11:3800:dc70:3fc9:9e52:eb91: 9 (Bad file descriptor)
2022-12-19 11:07:47 +0000 tr-udp.cc:383 [Warning] tr-udp.cc:383: Couldn't send to 2a06:5b05:8df9:4200:488e:9860:ddb5:b66a: 9 (Bad file descriptor)
2022-12-19 11:07:48 +0000 tr-udp.cc:383 [Warning] tr-udp.cc:383: Couldn't send to 2a06:5b05:8df9:4200:e460:b36c:fe0e:b412: 9 (Bad file descriptor)
2022-12-19 11:07:48 +0000 tr-udp.cc:383 [Warning] tr-udp.cc:383: Couldn't send to 2600:1017:a403:4c91:cad1:67dd:96a9:a920: 9 (Bad file descriptor)
2022-12-19 11:07:49 +0000 tr-udp.cc:383 [Warning] tr-udp.cc:383: Couldn't send to 2a06:c701:4a02:2500:89ec:f219:8301:e53: 9 (Bad file descriptor)
2022-12-19 11:07:50 +0000 tr-udp.cc:383 [Warning] tr-udp.cc:383: Couldn't send to 2a06:5b05:8df9:4200:488e:9860:ddb5:b66a: 9 (Bad file descriptor)
2022-12-19 11:07:51 +0000 tr-udp.cc:383 [Warning] tr-udp.cc:383: Couldn't send to 2a06:5b05:8df9:4200:e460:b36c:fe0e:b412: 9 (Bad file descriptor)
2022-12-19 11:07:51 +0000 tr-udp.cc:383 [Warning] tr-udp.cc:383: Couldn't send to 2600:1017:a403:4c91:cad1:67dd:96a9:a920: 9 (Bad file descriptor)
2022-12-19 11:07:52 +0000 tr-udp.cc:383 [Warning] tr-udp.cc:383: Couldn't send to 2804:41e0:fd11:3800:dc70:3fc9:9e52:eb91: 9 (Bad file descriptor)
2022-12-19 11:07:52 +0000 tr-udp.cc:383 [Warning] tr-udp.cc:383: Couldn't send to 2a06:c701:4a02:2500:89ec:f219:8301:e53: 9 (Bad file descriptor)
2022-12-19 11:07:56 +0000 tr-udp.cc:383 [Warning] tr-udp.cc:383: Couldn't send to 2a06:5b05:8df9:4200:488e:9860:ddb5:b66a: 9 (Bad file descriptor)
2022-12-19 11:07:58 +0000 tr-udp.cc:383 [Warning] tr-udp.cc:383: Couldn't send to 2a06:5b05:8df9:4200:e460:b36c:fe0e:b412: 9 (Bad file descriptor)
2022-12-19 11:07:58 +0000 tr-udp.cc:383 [Warning] tr-udp.cc:383: Couldn't send to 2600:1017:a403:4c91:cad1:67dd:96a9:a920: 9 (Bad file descriptor)
2022-12-19 11:07:58 +0000 tr-udp.cc:383 [Warning] tr-udp.cc:383: Couldn't send to 2a06:c701:4a02:2500:89ec:f219:8301:e53: 9 (Bad file descriptor)
2022-12-19 11:08:00 +0000 tr-udp.cc:383 [Warning] tr-udp.cc:383: Couldn't send to 2001:4c4d:2790:4e00:9ca2:1bc5:dd4b:c4af: 9 (Bad file descriptor)

### Which application of Transmission?

macOS app

### Which version of Transmission?

Beta 2 (9e6ffa351c)

**Comment by fredo-47** [comment]
I am seeing this too on Linux transmission-daemon 
4.0.0-beta.2.dev (5493ed644e)

**Comment by robd003** [comment]
I'm seeing this also but with IPv4 addresses too

**Comment by ckerr** [comment]
@GaryElshaw would it be possible for you to get a backtrace for this? It's clearly happening in `tr_session::tr_udp_core::sendto()` but I'm not sure where the call is coming from.

If you're comfortable with running a debugger, setting a breakpoint for `tr_session.cc:379` should do the trick.

Otherwise, another brute-force way to do it would be to insert this into the same place on line 379:

```c++
abort();
```

Since that will force Transmission to crash and should generate a crash report :smile:

**Comment by GaryElshaw** [comment]
Sorry Charles, i'm a bit confused about what i need to do. Happy to help, but i'm not understanding. I've just been looking for a file tr_session, but obviously lost.

**Comment by robd003** [comment]
Here? https://github.com/transmission/transmission/blob/6f1153cae49075e67caaa1e3929836fbd3211d24/libtransmission/tr-udp.cc#L379

**Comment by GaryElshaw** [comment]
I'm unsure, Rob.

**Comment by robd003** [comment]
Function signature matches: https://github.com/transmission/transmission/blob/6f1153cae49075e67caaa1e3929836fbd3211d24/libtransmission/tr-udp.cc#L320

**Comment by GaryElshaw** [comment]
@Coeur Help? Where should i be looking?

**Comment by Coeur** [comment]
@GaryElshaw
"9 (Bad file descriptor)" means that errno is 9, which is EBADF when you look at errno.h.
Charles wanted you to put a breakpoint on EBADF in tr_session::tr_udp_core::sendto (like in my screenshot), then copy the Thread that is hitting it (like in my copy-paste below).
![Capture d’écran 2022-12-24 à 22 04 55](https://user-images.githubusercontent.com/839992/209439271-b30494f0-738a-47e2-87fa-1ce72c8df2ab.png)

```
Thread 5#0	0x0000000101463244 in tr_session::tr_udp_core::sendto(void const*, unsigned long, sockaddr const*, unsigned int) const at /Users/User/Developer/transmission/libtransmission/tr-udp.cc:360
#1	0x00000001014732dc in utp_send_to(tr_session const*, unsigned char const*, unsigned long, sockaddr const*, unsigned int) at /Users/User/Developer/transmission/libtransmission/tr-utp.cc:112
#2	0x0000000101471e6c in utp_callback(utp_callback_arguments*) at /Users/User/Developer/transmission/libtransmission/tr-utp.cc:135
#3	0x00000001016fc620 in utp_call_sendto(struct_utp_context*, UTPSocket*, unsigned char const*, unsigned long, sockaddr const*, unsigned int, unsigned int) at /Users/User/Developer/transmission/third-party/libutp/utp_callbacks.cpp:206
#4	0x00000001016fd4dc in send_to_addr(struct_utp_context*, unsigned char const*, unsigned long, PackedSockAddr const&, int) at /Users/User/Developer/transmission/third-party/libutp/utp_internal.cpp:709
#5	0x00000001016fdfa0 in UTPSocket::send_data(unsigned char*, unsigned long, bandwidth_type_t, unsigned int) at /Users/User/Developer/transmission/third-party/libutp/utp_internal.cpp:764
#6	0x0000000101700140 in UTPSocket::send_packet(OutgoingPacket*) at /Users/User/Developer/transmission/third-party/libutp/utp_internal.cpp:922
#7	0x0000000101712744 in ::utp_connect(utp_socket *, const sockaddr *, socklen_t) at /Users/User/Developer/transmission/third-party/libutp/utp_internal.cpp:2810
#8	0x0000000101052ed0 in tr_peerIo::new_outgoing(tr_session*, tr_bandwidth*, tr_address const&, tr_port, std::__1::array<std::byte, 20ul> const&, bool, bool) at /Users/User/Developer/transmission/libtransmission/peer-io.cc:113
#9	0x000000010109ea44 in connect_helpers::initiateConnection(tr_peerMgr*, tr_swarm*, peer_atom&) at /Users/User/Developer/transmission/libtransmission/peer-mgr.cc:2733
#10	0x000000010109be74 in tr_peerMgr::makeNewPeerConnections(unsigned long) at /Users/User/Developer/transmission/libtransmission/peer-mgr.cc:2772
#11	0x000000010109b354 in tr_peerMgr::reconnectPulse() at /Users/User/Developer/transmission/libtransmission/peer-mgr.cc:2443
#12	0x000000010109d4cc in tr_peerMgr::bandwidthPulse() at /Users/User/Developer/transmission/libtransmission/peer-mgr.cc:2506
#13	0x00000001010a8a00 in tr_peerMgr::tr_peerMgr(tr_session*)::'lambda'()::operator()() const at /Users/User/Developer/transmission/libtransmission/peer-mgr.cc:521
#14	0x00000001010a8990 in decltype(static_cast<tr_peerMgr::tr_peerMgr(tr_session*)::'lambda'()&>(fp)()) std::__1::__invoke<tr_peerMgr::tr_peerMgr(tr_session*)::'lambda'()&>(tr_peerMgr::tr_peerMgr(tr_session*)::'lambda'()&) at /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/type_traits:3918
#15	0x00000001010a8948 in void std::__1::__invoke_void_return_wrapper<void, true>::__call<tr_peerMgr::tr_peerMgr(tr_session*)::'lambda'()&>(tr_peerMgr::tr_peerMgr(tr_session*)::'lambda'()&) at /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/__functional/invoke.h:61
#16	0x00000001010a8920 in std::__1::__function::__alloc_func<tr_peerMgr::tr_peerMgr(tr_session*)::'lambda'(), std::__1::allocator<tr_peerMgr::tr_peerMgr(tr_session*)::'lambda'()>, void ()>::operator()() at /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/__functional/function.h:178
#17	0x00000001010a4868 in std::__1::__function::__func<tr_peerMgr::tr_peerMgr(tr_session*)::'lambda'(), std::__1::allocator<tr_peerMgr::tr_peerMgr(tr_session*)::'lambda'()>, void ()>::operator()() at /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/__functional/function.h:352
#18	0x000000010100344c in std::__1::__function::__value_func<void ()>::operator()() const at /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/__functional/function.h:505
#19	0x0000000101002474 in std::__1::function<void ()>::operator()() const at /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/__functional/function.h:1182
#20	0x00000001015942d0 in libtransmission::EvTimer::handleTimer() at /Users/User/Developer/transmission/libtransmission/timer-ev.cc:143
#21	0x0000000101593104 in libtransmission::EvTimer::onTimer(int, short, void*) at /Users/User/Developer/transmission/libtransmission/timer-ev.cc:135
#22	0x0000000101669b98 in event_persist_closure at /Users/User/Developer/transmission/third-party/libevent/event.c:1623
#23	0x0000000101667224 in event_process_active_single_queue at /Users/User/Developer/transmission/third-party/libevent/event.c:1682
#24	0x0000000101655618 in event_process_active at /Users/User/Developer/transmission/third-party/libevent/event.c:1783
#25	0x000000010165196c in event_base_loop at /Users/User/Developer/transmission/third-party/libevent/event.c:2006
#26	0x00000001010009a0 in tr_session_thread_impl::sessionThreadFunc(event_base*) at /Users/User/Developer/transmission/libtransmission/session-thread.cc:245
#27	0x00000001010065ac in decltype(*(static_cast<tr_session_thread_impl*>(fp0)).*fp(static_cast<event_base*>(fp1))) std::__1::__invoke<void (tr_session_thread_impl::*)(event_base*), tr_session_thread_impl*, event_base*, void>(void (tr_session_thread_impl::*&&)(event_base*), tr_session_thread_impl*&&, event_base*&&) at /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/type_traits:3859
#28	0x000000010100644c in void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (tr_session_thread_impl::*)(event_base*), tr_session_thread_impl*, event_base*, 2ul, 3ul>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (tr_session_thread_impl::*)(event_base*), tr_session_thread_impl*, event_base*>&, std::__1::__tuple_indices<2ul, 3ul>) at /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/thread:287
#29	0x00000001010050a8 in void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (tr_session_thread_impl::*)(event_base*), tr_session_thread_impl*, event_base*> >(void*) at /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr/include/c++/v1/thread:298
#30	0x00000001029b55d4 in _pthread_start ()
```

**Comment by ckerr** [comment]
Woot, that's the stuff, thank you @Coeur, @GaryElshaw, and @robd003

**Comment by ckerr** [comment]
```
#0	0x0000000101463244 in tr_session::tr_udp_core::sendto(void const*, unsigned long, sockaddr const*, unsigned int) const at /Users/User/Developer/transmission/libtransmission/tr-udp.cc:360
#1	0x00000001014732dc in utp_send_to(tr_session const*, unsigned char const*, unsigned long, sockaddr const*, unsigned int) at /Users/User/Developer/transmission/libtransmission/tr-utp.cc:112
#2	0x0000000101471e6c in utp_callback(utp_callback_arguments*) at /Users/User/Developer/transmission/libtransmission/tr-utp.cc:135
#3	0x00000001016fc620 in utp_call_sendto(struct_utp_context*, UTPSocket*, unsigned char const*, unsigned long, sockaddr const*, unsigned int, unsigned int) at /Users/User/Developer/transmission/third-party/libutp/utp_callbacks.cpp:206
#4	0x00000001016fd4dc in send_to_addr(struct_utp_context*, unsigned char const*, unsigned long, PackedSockAddr const&, int) at /Users/User/Developer/transmission/third-party/libutp/utp_internal.cpp:709
#5	0x00000001016fdfa0 in UTPSocket::send_data(unsigned char*, unsigned long, bandwidth_type_t, unsigned int) at /Users/User/Developer/transmission/third-party/libutp/utp_internal.cpp:764
#6	0x0000000101700140 in UTPSocket::send_packet(OutgoingPacket*) at /Users/User/Developer/transmission/third-party/libutp/utp_internal.cpp:922
#7	0x0000000101712744 in ::utp_connect(utp_socket *, const sockaddr *, socklen_t) at /Users/User/Developer/transmission/third-party/libutp/utp_internal.cpp:2810
#8	0x0000000101052ed0 in tr_peerIo::new_outgoing(tr_session*, tr_bandwidth*, tr_address const&, tr_port, std::__1::array<std::byte, 20ul> const&, bool, bool) at /Users/User/Developer/transmission/libtransmission/peer-io.cc:113
```

This makes sense to me -- Transmission is trying an outgoing UTP connection but it doesn't work because the peer isn't connectable. This is working as intended; I don't think any behavior needs to change except for de-emphasizing or removing the error message.

**Comment by GaryElshaw** [comment]
Thanks Antoine, sometimes i need a very detailed roadmap!

**Comment by ckerr** [comment]
@GaryElshaw what happens if you run a build from this branch: https://github.com/transmission/transmission/pull/4469

**Comment by GaryElshaw** [comment]
Still the same i'm afraid, Charles.

2022-12-25 16:36:04 +0000 tr-udp.cc:298 [Warning] tr-udp.cc:298: Couldn't send to 2a06:c701:4a02:2500:89ec:f219:8301:e53: 9 (Bad file descriptor)
2022-12-25 16:36:05 +0000 tr-udp.cc:298 [Warning] tr-udp.cc:298: Couldn't send to 2600:1017:a403:4c91:cad1:67dd:96a9:a920: 9 (Bad file descriptor)
2022-12-25 16:36:06 +0000 tr-udp.cc:298 [Warning] tr-udp.cc:298: Couldn't send to 2a06:5b05:8df9:4200:488e:9860:ddb5:b66a: 9 (Bad file descriptor)
2022-12-25 16:36:07 +0000 tr-udp.cc:298 [Warning] tr-udp.cc:298: Couldn't send to 2a06:c701:4a02:2500:89ec:f219:8301:e53: 9 (Bad file descriptor)
2022-12-25 16:36:08 +0000 tr-udp.cc:298 [Warning] tr-udp.cc:298: Couldn't send to 2600:1017:a403:4c91:cad1:67dd:96a9:a920: 9 (Bad file descriptor)
2022-12-25 16:36:09 +0000 tr-udp.cc:298 [Warning] tr-udp.cc:298: Couldn't send to 2a06:5b05:8df9:4200:488e:9860:ddb5:b66a: 9 (Bad file descriptor)
2022-12-25 16:36:12 +0000 peer-mgr.cc:1023 [Debug] BBC.Cant.Get.You.Out.of.My.Head.720p.x265.AAC.MVGroup.org.mkv: setting [189.78.60.225]:26671 do_purge flag because we got an ERANGE, EMSGSIZE, or ENOTCONN error
2022-12-25 16:36:13 +0000 tr-udp.cc:298 [Warning] tr-udp.cc:298: Couldn't send to 2a06:c701:4a02:2500:89ec:f219:8301:e53: 9 (Bad file descriptor)
2022-12-25 16:36:15 +0000 tr-udp.cc:298 [Warning] tr-udp.cc:298: Couldn't send to 2600:1017:a403:4c91:cad1:67dd:96a9:a920: 9 (Bad file descriptor)
2022-12-25 16:36:15 +0000 tr-udp.cc:298 [Warning] tr-udp.cc:298: Couldn't send to 2a06:5b05:8df9:4200:488e:9860:ddb5:b66a: 9 (Bad file descriptor)
2022-12-25 16:36:23 +0000 tr-udp.cc:298 [Warning] tr-udp.cc:298: Couldn't send to 2001:4c4d:2790:4e00:9ca2:1bc5:dd4b:c4af: 9 (Bad file descriptor)
2022-12-25 16:36:26 +0000 tr-udp.cc:298 [Warning] tr-udp.cc:298: Couldn't send to 2001:4c4d:2790:4e00:9ca2:1bc5:dd4b:c4af: 9 (Bad file descriptor)
2022-12-25 16:36:27 +0000 tr-udp.cc:298 [Warning] tr-udp.cc:298: Couldn't send to 2a02:6ea0:c43f:1::b51e: 9 (Bad file descriptor)
2022-12-25 16:36:30 +0000 tr-udp.cc:298 [Warning] tr-udp.cc:298: Couldn't send to 2a02:a31a:c243:bc00:38d4:7a00:52c1:d57b: 9 (Bad file descriptor)
2022-12-25 16:36:30 +0000 tr-udp.cc:298 [Warning] tr-udp.cc:298: Couldn't send to 2a02:6ea0:c43f:1::b51e: 9 (Bad file descriptor)
2022-12-25 16:36:33 +0000 tr-udp.cc:298 [Warning] tr-udp.cc:298: Couldn't send to 2001:4c4d:2790:4e00:9ca2:1bc5:dd4b:c4af: 9 (Bad file descriptor)
2022-12-25 16:36:33 +0000 tr-udp.cc:298 [Warning] tr-udp.cc:298: Couldn't send to 2a02:a31a:c243:bc00:38d4:7a00:52c1:d57b: 9 (Bad file descriptor)

**Comment by ckerr** [comment]
@GaryElshaw could you paste the log messages from tr-udp leading up to that? I'm particularly interested in the messages during setup or any referring to sockets or binding.

**Comment by GaryElshaw** [comment]
2022-12-25 16:34:40 +0000 session.cc:551 [Info] session.cc:551: Transmission version 4.0.0-beta.2.dev (70e9bb21bc) starting
2022-12-25 16:34:40 +0000 cache.cc:120 [Debug] cache.cc:120: Maximum cache size set to 4.00 MB (244 blocks)
2022-12-25 16:34:40 +0000 net.cc:335 [Debug] net.cc:335: Bound socket 6 to port 57564 on 0.0.0.0
2022-12-25 16:34:40 +0000 session.cc:326 [Info] session.cc:326: Listening to incoming peer connections on [0.0.0.0]:57564
2022-12-25 16:34:40 +0000 net.cc:335 [Debug] net.cc:335: Bound socket 7 to port 57564 on ::
2022-12-25 16:34:40 +0000 session.cc:326 [Info] session.cc:326: Listening to incoming peer connections on [::]:57564
2022-12-25 16:34:40 +0000 tr-udp.cc:169 [Info] [0.0.0.0]:57564: Bound UDP IPv4 address {:s}
2022-12-25 16:34:40 +0000 tr-udp.cc:180 [Warning] tr-udp.cc:180: Unable to find global IPv6 address
2022-12-25 16:34:40 +0000 tr-lpd.cc:282 [Debug] tr-lpd.cc:282: Initialising Local Peer Discovery
2022-12-25 16:34:40 +0000 tr-lpd.cc:385 [Debug] tr-lpd.cc:385: Local Peer Discovery initialised
2022-12-25 16:34:40 +0000 tr-dht.cc:139 [Debug] tr-dht.cc:139: Starting DHT on port 57564
2022-12-25 16:34:40 +0000 rpc-server.cc:848 [Debug] rpc-server.cc:848: setting password-enabled to 'false'
2022-12-25 16:34:40 +0000 rpc-server.cc:810 [Info] rpc-server.cc:810: Added '127.0.0.1' to host whitelist
2022-12-25 16:34:40 +0000 rpc-server.cc:810 [Info] rpc-server.cc:810: Added '::1' to host whitelist
2022-12-25 16:34:40 +0000 rpc-server.cc:830 [Debug] rpc-server.cc:830: setting our username to 'admin'
2022-12-25 16:34:40 +0000 rpc-server.cc:842 [Debug] rpc-server.cc:842: setting our salted password to '{9904cf998ad998452a4918bcebd0cfab072b775flKPVJOeE'
2022-12-25 16:34:40 +0000 rpc-server.cc:937 [Info] rpc-server.cc:937: Serving RPC and Web requests from '/usr/local/share/transmission/public_html'
2022-12-25 16:34:40 +0000 tr-lpd.cc:282 [Debug] tr-lpd.cc:282: Initialising Local Peer Discovery
2022-12-25 16:34:40 +0000 tr-lpd.cc:385 [Debug] tr-lpd.cc:385: Local Peer Discovery initialised

**Comment by ckerr** [comment]
@GaryElshaw that's helpful!

For reference could you provide the same log for 4.0.0-beta.1?

**Comment by ckerr** [comment]
Asking because I suspect https://github.com/transmission/transmission/issues/4410 might be related to this

**Comment by GaryElshaw** [comment]
Here we go....

2022-12-26 03:26:46 +0000 session.cc:746 [Info] session.cc:746: Transmission version 3.10.10-dev (1a42769e41) starting
2022-12-26 03:26:46 +0000 cache.cc:120 [Debug] cache.cc:120: Maximum cache size set to 4.00 MB (244 blocks)
2022-12-26 03:26:46 +0000 tr-lpd.cc:285 [Debug] tr-lpd.cc:285: Initialising Local Peer Discovery
2022-12-26 03:26:46 +0000 tr-lpd.cc:388 [Debug] tr-lpd.cc:388: Local Peer Discovery initialised
2022-12-26 03:26:46 +0000 rpc-server.cc:862 [Debug] rpc-server.cc:862: setting password-enabled to 'false'
2022-12-26 03:26:46 +0000 rpc-server.cc:824 [Info] rpc-server.cc:824: Added '127.0.0.1' to host whitelist
2022-12-26 03:26:46 +0000 rpc-server.cc:824 [Info] rpc-server.cc:824: Added '::1' to host whitelist
2022-12-26 03:26:46 +0000 rpc-server.cc:844 [Debug] rpc-server.cc:844: setting our username to 'admin'
2022-12-26 03:26:46 +0000 rpc-server.cc:856 [Debug] rpc-server.cc:856: setting our salted password to '{9b6cb750256a8644dad370e89c0a8c6900e951506OBUfOX.'
2022-12-26 03:26:46 +0000 rpc-server.cc:1099 [Info] rpc-server.cc:1099: Serving RPC and Web requests from '/usr/local/share/transmission/public_html'
2022-12-26 03:26:46 +0000 net.cc:475 [Debug] net.cc:475: Bound socket 7 to port 57564 on 0.0.0.0
2022-12-26 03:26:46 +0000 session.cc:312 [Info] session.cc:312: Listening to incoming peer connections on [0.0.0.0]:57564
2022-12-26 03:26:46 +0000 net.cc:475 [Debug] net.cc:475: Bound socket 8 to port 57564 on ::
2022-12-26 03:26:46 +0000 session.cc:312 [Info] session.cc:312: Listening to incoming peer connections on [::]:57564
2022-12-26 03:26:46 +0000 tr-dht.cc:443 [Info] tr-dht.cc:443: Initializing DHT
2022-12-26 03:26:46 +0000 tr-dht.cc:355 [Debug] tr-dht.cc:355: Bootstrapping from 254 IPv4 nodes
2022-12-26 03:26:46 +0000 tr-dht.cc:516 [Debug] tr-dht.cc:516: DHT initialized
2022-12-26 03:26:46 +0000 web.cc:591 [Debug] web.cc:591: CURLOPT_SHARE ended at 6
2022-12-26 03:26:46 +0000 web.cc:126 [Info] web.cc:126: Will verify tracker certs using envvar CURL_CA_BUNDLE: none
2022-12-26 03:26:46 +0000 web.cc:127 [Info] web.cc:127: NB: this only works if you built against libcurl with openssl or gnutls, NOT nss
2022-12-26 03:26:46 +0000 web.cc:128 [Info] web.cc:128: NB: Invalid certs will appear as 'Could not connect to tracker' like many other errors
2022-12-26 03:26:46 +0000 tr-lpd.cc:285 [Debug] tr-lpd.cc:285: Initialising Local Peer Discovery
2022-12-26 03:26:46 +0000 tr-lpd.cc:388 [Debug] tr-lpd.cc:388: Local Peer Discovery initialised
2022-12-26 03:26:46 +0000 rpc-server.cc:824 [Info] rpc-server.cc:824: Added '127.0.0.1' to host whitelist


Still seeing the dreaded `2022-12-26 03:27:01 +0000 tr-udp.cc:427 [Warning] tr-udp.cc:427: Couldn't send to 2001:448a:50c2:d70c:16f:d9:6081:5ea1: 9 (Bad file descriptor)`

**Comment by ckerr** [comment]
@GaryElshaw I've pushed fresh commits to  https://github.com/transmission/transmission/pull/4469 that may solve the problem. I'm traveling for the holidays and don't have access to a good testing environment though, so I haven't been able to give it a test-drive.

If you test it out and the problem persists, please paste the same kinds of log information as before. Thank you!

**Comment by GaryElshaw** [comment]
I think that's cracked it Charles!

**Comment by fredo-47** [comment]
I am still getting these messages, with transmission daemon on Linux (5ce503f1ab):

`[2022-12-28 12:10:25.862] WRN tr-udp.cc:295 Couldn't send to 2002:5881:bc9f::5881:bc9f: 9 (Bad file descriptor) (/home/Transmission/libtransmission/tr-udp.cc:295)
[2022-12-28 12:10:28.862] WRN tr-udp.cc:295 Couldn't send to 2002:5881:bc9f::5881:bc9f: 9 (Bad file descriptor) (/home/Transmission/libtransmission/tr-udp.cc:295)
[2022-12-28 12:10:35.862] WRN tr-udp.cc:295 Couldn't send to 2002:5881:bc9f::5881:bc9f: 9 (Bad file descriptor) (/home/Transmission/libtransmission/tr-udp.cc:295)
[2022-12-28 12:11:36.862] WRN tr-udp.cc:295 Couldn't send to 2601:246:8102:de00::e150: 9 (Bad file descriptor) (/home/Transmission/libtransmission/tr-udp.cc:295)
[2022-12-28 12:11:37.947] WRN tr-udp.cc:295 Couldn't send to 2a00:1851:18:210f:9098:3805:56ed:3: 9 (Bad file descriptor) (/home/Transmission/libtransmission/tr-udp.cc:295)
[2022-12-28 12:11:37.947] WRN tr-udp.cc:295 Couldn't send to 2601:246:8102:de00::283b: 9 (Bad file descriptor) (/home/Transmission/libtransmission/tr-udp.cc:295)
[2022-12-28 12:11:39.265] WRN tr-udp.cc:295 Couldn't send to 2601:246:8102:de00::283b: 9 (Bad file descriptor) (/home/Transmission/libtransmission/tr-udp.cc:295)
[2022-12-28 12:11:39.265] WRN tr-udp.cc:295 Couldn't send to 2001:1c03:3f11:4d00:bd68:ec73:c13:51ce: 9 (Bad file descriptor) (/home/Transmission/libtransmission/tr-udp.cc:295)
[2022-12-28 12:11:39.944] WRN tr-udp.cc:295 Couldn't send to fdd5:4d62:b83a:1:bd7e:4ac5:7409:fa7c: 9 (Bad file descriptor) (/home/Transmission/libtransmission/tr-udp.cc:295)
[2022-12-28 12:11:39.944] WRN tr-udp.cc:295 Couldn't send to 2601:246:8102:de00::e150: 9 (Bad file descriptor) (/home/Transmission/libtransmission/tr-udp.cc:295)
[2022-12-28 12:11:41.108] WRN tr-udp.cc:295 Couldn't send to 2a00:1851:18:210f:9098:3805:56ed:3: 9 (Bad file descriptor) (/home/Transmission/libtransmission/tr-udp.cc:295)
[2022-12-28 12:11:41.108] WRN tr-udp.cc:295 Couldn't send to 2601:246:8102:de00::283b: 9 (Bad file descriptor) (/home/Transmission/libtransmission/tr-udp.cc:295)
[2022-12-28 12:11:41.108] WRN tr-udp.cc:295 Couldn't send to 2601:246:8102:de00::790c: 9 (Bad file descriptor) (/home/Transmission/libtransmission/tr-udp.cc:295)
[2022-12-28 12:11:41.916] WRN tr-udp.cc:295 Couldn't send to 2603:8081:7600:58a4::1000: 9 (Bad file descriptor) (/home/Transmission/libtransmission/tr-udp.cc:295)
[2022-12-28 12:11:41.916] WRN tr-udp.cc:295 Couldn't send to 2603:8081:7600:58a4::1000: 9 (Bad file descriptor) (/home/Transmission/libtransmission/tr-udp.cc:295)
[2022-12-28 12:11:43.085] WRN tr-udp.cc:295 Couldn't send to 2601:246:8102:de00::283b: 9 (Bad file descriptor) (/home/Transmission/libtransmission/tr-udp.cc:295)
[2022-12-28 12:11:43.085] WRN tr-udp.cc:295 Couldn't send to 2001:1c03:3f11:4d00:bd68:ec73:c13:51ce: 9 (Bad file descriptor) (/home/Transmission/libtransmission/tr-udp.cc:295)
[2022-12-28 12:11:43.085] WRN tr-udp.cc:295 Couldn't send to fdd5:4d62:b83a:1:bd7e:4ac5:7409:fa7c: 9 (Bad file descriptor) (/home/Transmission/libtransmission/tr-udp.cc:295)
[2022-12-28 12:11:43.948] WRN tr-udp.cc:295 Couldn't send to 2601:246:8102:de00::8953: 9 (Bad file descriptor) (/home/Transmission/libtransmission/tr-udp.cc:295)
[2022-12-28 12:11:43.948] WRN tr-udp.cc:295 Couldn't send to 2607:fea8:28a2:c00::8c1e: 9 (Bad file descriptor) (/home/Transmission/libtransmission/tr-udp.cc:295)
[2022-12-28 12:11:43.948] WRN tr-udp.cc:295 Couldn't send to 2600:6c64:607f:cc00:9550:5346:ba5e:3c75: 9 (Bad file descriptor) (/home/Transmission/libtransmission/tr-udp.cc:295)
[2022-12-28 12:11:45.135] WRN tr-udp.cc:295 Couldn't send to 2601:246:8102:de00::790c: 9 (Bad file descriptor) (/home/Transmission/libtransmission/tr-udp.cc:295)
[2022-12-28 12:11:45.135] WRN tr-udp.cc:295 Couldn't send to 2603:8081:7600:58a4::1000: 9 (Bad file descriptor) (/home/Transmission/libtransmission/tr-udp.cc:295)
[2022-12-28 12:11:45.135] WRN tr-udp.cc:295 Couldn't send to 2603:8081:7600:58a4::1000: 9 (Bad file descriptor) (/home/Transmission/libtransmission/tr-udp.cc:295)
[2022-12-28 12:11:46.862] WRN tr-udp.cc:295 Couldn't send to 2601:246:8102:de00::e150: 9 (Bad file descriptor) (/home/Transmission/libtransmission/tr-udp.cc:295)
[2022-12-28 12:11:46.862] WRN tr-udp.cc:295 Couldn't send to 2601:246:8102:de00::8953: 9 (Bad file descriptor) (/home/Transmission/libtransmission/tr-udp.cc:295)
[2022-12-28 12:11:46.862] WRN tr-udp.cc:295 Couldn't send to 2607:fea8:28a2:c00::8c1e: 9 (Bad file descriptor) (/home/Transmission/libtransmission/tr-udp.cc:295)
[2022-12-28 12:11:46.862] WRN tr-udp.cc:295 Couldn't send to 2a00:1851:18:210f:9098:3805:56ed:3: 9 (Bad file descriptor) (/home/Transmission/libtransmission/tr-udp.cc:295)
[2022-12-28 12:11:48.195] WRN tr-udp.cc:295 Couldn't send to 2601:246:8102:de00::a3fc: 9 (Bad file descriptor) (/home/Transmission/libtransmission/tr-udp.cc:295)
[2022-12-28 12:11:48.195] WRN tr-udp.cc:295 Couldn't send to 2600:6c64:607f:cc00:9550:5346:ba5e:3c75: 9 (Bad file descriptor) (/home/Transmission/libtransmission/tr-udp.cc:295)
[2022-12-28 12:11:48.195] WRN tr-udp.cc:295 Too many messages like this! I won't log this message anymore this session. (/home/Transmission/libtransmission/tr-udp.cc:295)`

**Comment by ckerr** [comment]
@fredo-47  could you paste the log messages from tr-udp leading up to that? I'm particularly interested in the messages during setup or any referring to sockets or binding

**Comment by fredo-47** [comment]
From tr-udp, there is only these two (after re-starting the daemon):
`[2022-12-28 16:19:23.323] inf [0.0.0.0]:51314 Bound UDP IPv4 address {:s} (/home/Transmission/libtransmission/tr-udp.cc:169)`
`[2022-12-28 16:19:23.323] WRN tr-udp.cc:190 Couldn't bind IPv6 socket ::: Address already in use (98) (/home/Transmission/libtransmission/tr-udp.cc:190)`
I don't know what this means, because I do not have an IP6 address.

**Comment by fredo-47** [comment]
Having it run with message-level 6 doesn't produce additional message compared to the above.
See here with latest 4.0.0-beta.2.dev (2b90a5fd55):
`[2022-12-29 19:44:37.643] inf [0.0.0.0]:51314 Bound UDP IPv4 address {:s} (/home/Transmission/libtransmission/tr-udp.cc:169)`
`[2022-12-29 19:44:37.643] WRN tr-udp.cc:190 Couldn't bind IPv6 socket ::: Address already in use (98) (/home/Transmission/libtransmission/tr-udp.cc:190)`
And then several times
`[2022-12-29 19:49:01.733] WRN tr-udp.cc:295 Couldn't send to 2002:5881:bc9f::5881:bc9f: 9 (Bad file descriptor) (/home/Transmission/libtransmission/tr-udp.cc:295)`

**Comment by ckerr** [comment]
> [2022-12-28 16:19:23.323] WRN tr-udp.cc:190 Couldn't bind IPv6 socket ::: Address already in use (98) (/home/Transmission/libtransmission/tr-udp.cc:190)

This is the heart of the variant of this issue that @fredo-47 is hitting, but it's kind of separate from the one that @GaryElshaw was seeing so just for bookeeping's sake I think I'd like to close this ticket and handle the separate issue in a separate ticket.

@fredo-47 could you please file a new ticket about "Couldn't bind IPv6 socket ::: Address already in use"?
