### ISSUE TITLE
Couldn't bind IPv6 socket ::: Address already in use

### ISSUE THREAD

**Issue by fredo-47** [transmission/transmission#4516]
### What is the issue?

As a follow-up to https://github.com/transmission/transmission/issues/4406, I'd like to report that I am getting lots of these tr-udp warnings:
`[2022-12-29 19:49:01.733] WRN tr-udp.cc:295 Couldn't send to 2002:5881:bc9f::5881:bc9f: 9 (Bad file descriptor) (/home/Transmission/libtransmission/tr-udp.cc:295)`
According to @ckerr , this preceeding message is important:
`[2022-12-28 16:19:23.323] WRN tr-udp.cc:190 Couldn't bind IPv6 socket ::: Address already in use (98) (/home/Transmission/libtransmission/tr-udp.cc:190)`

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

4.0.0-beta.2.dev (2b90a5f)

**Comment by ckerr** [comment]
Fixed by #4513 :)

**Comment by fredo-47** [comment]
The message `WRN tr-udp.cc:190 Couldn't bind IPv6 socket ::: Address already in use` is indeed gone.

However, I am still getting lots of these:
`[2023-01-02 15:18:33.522] WRN tr-udp.cc:258 Couldn't send to [2601:8b:8580:7c60::9a00]:18939: 101 (Network is unreachable)`
[...]
`[2023-01-02 15:24:08.588] WRN tr-udp.cc:258 Too many messages like this! I won't log this message anymore this session.`

Version 806491232b

I will open another separate issue.

**Comment by ckerr** [comment]
:dizzy:
