### ISSUE TITLE
tr-udp.cc: Couldn't send to [xxxx:xx:xxxx:xxxx::xxxx]:yyyyy: 101 (Network is unreachable)

### ISSUE THREAD

**Issue by fredo-47** [transmission/transmission#4517]
### What is the issue?

My transmission-daemon's message log still gets flooded by the same warnings from tr-udp as reported in the closed issues #4406  and #4516 :

`[2023-01-02 15:18:33.522] WRN tr-udp.cc:258 Couldn't send to [2601:8b:8580:7c60::9a00]:18939: 101 (Network is unreachable) (/home/Transmission/libtransmission/tr-udp.cc:258)
[2023-01-02 15:18:35.732] WRN tr-udp.cc:258 Couldn't send to [2601:8b:8402:ad00::ff85]:64329: 101 (Network is unreachable) (/home/Transmission/libtransmission/tr-udp.cc:258)
[2023-01-02 15:18:35.732] WRN tr-udp.cc:258 Couldn't send to [2601:8b:8580:7c60::9a00]:18939: 101 (Network is unreachable) (/home/Transmission/libtransmission/tr-udp.cc:258)
[2023-01-02 15:18:39.523] WRN tr-udp.cc:258 Couldn't send to [2601:8b:8402:ad00::ff85]:64329: 101 (Network is unreachable) (/home/Transmission/libtransmission/tr-udp.cc:258)
[2023-01-02 15:18:42.522] WRN tr-udp.cc:258 Couldn't send to [2601:8b:8580:7c60::9a00]:18939: 101 (Network is unreachable) (/home/Transmission/libtransmission/tr-udp.cc:258)
[2023-01-02 15:18:45.522] WRN tr-udp.cc:258 Couldn't send to [2601:8b:8402:ad00::ff85]:64329: 101 (Network is unreachable) (/home/Transmission/libtransmission/tr-udp.cc:258)
[2023-01-02 15:19:06.522] WRN tr-udp.cc:258 Couldn't send to [2607:fa49:3c3e:a600::4246]:20431: 101 (Network is unreachable) (/home/Transmission/libtransmission/tr-udp.cc:258)
[2023-01-02 15:19:09.522] WRN tr-udp.cc:258 Couldn't send to [2607:fa49:3c3e:a600::4246]:20431: 101 (Network is unreachable) (/home/Transmission/libtransmission/tr-udp.cc:258)
[2023-01-02 15:19:15.523] WRN tr-udp.cc:258 Couldn't send to [2607:fa49:3c3e:a600::4246]:20431: 101 (Network is unreachable) (/home/Transmission/libtransmission/tr-udp.cc:258)
[2023-01-02 15:20:13.523] WRN tr-udp.cc:258 Couldn't send to [2603:8000:5e00:2207::11d6]:60954: 101 (Network is unreachable) (/home/Transmission/libtransmission/tr-udp.cc:258)
[2023-01-02 15:20:14.597] WRN tr-udp.cc:258 Couldn't send to [2001:0:284a:364:89a:17c6:a199:83db]:5034: 101 (Network is unreachable) (/home/Transmission/libtransmission/tr-udp.cc:258)
[2023-01-02 15:20:16.523] WRN tr-udp.cc:258 Couldn't send to [2603:8000:5e00:2207::11d6]:60954: 101 (Network is unreachable) (/home/Transmission/libtransmission/tr-udp.cc:258)
[2023-01-02 15:20:18.691] WRN tr-udp.cc:258 Couldn't send to [2001:0:284a:364:89a:17c6:a199:83db]:5034: 101 (Network is unreachable) (/home/Transmission/libtransmission/tr-udp.cc:258)
[2023-01-02 15:20:22.523] WRN tr-udp.cc:258 Couldn't send to [2603:8000:5e00:2207::11d6]:60954: 101 (Network is unreachable) (/home/Transmission/libtransmission/tr-udp.cc:258)
[2023-01-02 15:20:24.691] WRN tr-udp.cc:258 Couldn't send to [2001:0:284a:364:89a:17c6:a199:83db]:5034: 101 (Network is unreachable) (/home/Transmission/libtransmission/tr-udp.cc:258)
[2023-01-02 15:21:24.523] WRN tr-udp.cc:258 Couldn't send to [fde6:7a:7d20:18f6::10b8]:26351: 101 (Network is unreachable) (/home/Transmission/libtransmission/tr-udp.cc:258)
[2023-01-02 15:21:27.523] WRN tr-udp.cc:258 Couldn't send to [fde6:7a:7d20:18f6::10b8]:26351: 101 (Network is unreachable) (/home/Transmission/libtransmission/tr-udp.cc:258)
[2023-01-02 15:21:32.523] WRN tr-udp.cc:258 Couldn't send to [2600:1009:a101:8d17:411d:164a:d30:5202]:10807: 101 (Network is unreachable) (/home/Transmission/libtransmission/tr-udp.cc:258)
[2023-01-02 15:21:34.716] WRN tr-udp.cc:258 Couldn't send to [fde6:7a:7d20:18f6::10b8]:26351: 101 (Network is unreachable) (/home/Transmission/libtransmission/tr-udp.cc:258)
[2023-01-02 15:21:35.601] WRN tr-udp.cc:258 Couldn't send to [2600:1009:a101:8d17:411d:164a:d30:5202]:10807: 101 (Network is unreachable) (/home/Transmission/libtransmission/tr-udp.cc:258)
[2023-01-02 15:21:41.523] WRN tr-udp.cc:258 Couldn't send to [2600:1009:a101:8d17:411d:164a:d30:5202]:10807: 101 (Network is unreachable) (/home/Transmission/libtransmission/tr-udp.cc:258)
[2023-01-02 15:23:11.522] WRN tr-udp.cc:258 Couldn't send to [2a02:587:5f09:4c00:452c:be8c:49ec:10c2]:19738: 101 (Network is unreachable) (/home/Transmission/libtransmission/tr-udp.cc:258)
[2023-01-02 15:23:13.700] WRN tr-udp.cc:258 Couldn't send to [2a02:587:5f09:4c00:452c:be8c:49ec:10c2]:19738: 101 (Network is unreachable) (/home/Transmission/libtransmission/tr-udp.cc:258)
[2023-01-02 15:23:20.522] WRN tr-udp.cc:258 Couldn't send to [2a02:587:5f09:4c00:452c:be8c:49ec:10c2]:19738: 101 (Network is unreachable) (/home/Transmission/libtransmission/tr-udp.cc:258)
[2023-01-02 15:24:07.523] WRN tr-udp.cc:258 Couldn't send to [2a00:1851:17:1485:9098:3805:56ed:2]:26610: 101 (Network is unreachable) (/home/Transmission/libtransmission/tr-udp.cc:258)
[2023-01-02 15:24:07.524] WRN tr-udp.cc:258 Couldn't send to [2601:246:8102:de00::e150]:19795: 101 (Network is unreachable) (/home/Transmission/libtransmission/tr-udp.cc:258)
[2023-01-02 15:24:07.524] WRN tr-udp.cc:258 Couldn't send to [2a00:1851:18:7d97:246f:8c3d:47f1:4]:26610: 101 (Network is unreachable) (/home/Transmission/libtransmission/tr-udp.cc:258)
[2023-01-02 15:24:07.524] WRN tr-udp.cc:258 Couldn't send to [2601:246:8102:de00::d4af]:19795: 101 (Network is unreachable) (/home/Transmission/libtransmission/tr-udp.cc:258)
[2023-01-02 15:24:07.524] WRN tr-udp.cc:258 Couldn't send to [2a00:1851:17:f9d:246f:8c3d:47f1:3]:26610: 101 (Network is unreachable) (/home/Transmission/libtransmission/tr-udp.cc:258)
[2023-01-02 15:24:08.588] WRN tr-udp.cc:258 Couldn't send to [2a00:1851:8017:e40c:9098:3805:56ed:2]:26610: 101 (Network is unreachable) (/home/Transmission/libtransmission/tr-udp.cc:258)`

`[2023-01-02 15:24:08.588] WRN tr-udp.cc:258 Too many messages like this! I won't log this message anymore this session. (/home/Transmission/libtransmission/tr-udp.cc:258)`

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

8064912

**Comment by ckerr** [comment]
Looks like this bug was introduced in 36edd516aa550c8b08f0b18fd9cc3e51b843e3f4 when a refactor removed the `tr_net_hasIPv6()` check.

**Comment by ckerr** [comment]
@fredo-47 what happens when you visit http://test-ipv6.com from the same computer that you're running Transmission on?

I don't want your IP address of course, but I am trying to understand whether ipv6 works on your setup.

**Comment by fredo-47** [comment]
@ckerr , this is what I get there:
(as I said earlier, I do not have ipv6)
![ipv6](https://user-images.githubusercontent.com/30537162/213394136-3377a77a-4e14-455a-98d0-7f49d6179441.jpg)

**Comment by ckerr** [comment]
Thanks for the info!

The original variant of this bug was an actual regression in Transmission with udp + ipv6.

The current one is that users without ipv6 are going to get this annoying message in the log. Which still should be fixed, but IMO it's not a blocker for 4.0.0 and right now I'm thinking more in terms of "do I really want to touch this networking code again right before a stable release" so I'm going to remove the milestone. :smile_cat: 

> (as I said earlier, I do not have ipv6)

Right, but there are different levels of "do not have ipv6" so I wanted to make sure what was going on before deciding on this issue for 4.0.0

**Comment by fredo-47** [comment]
@ckerr , I'm afraid I am still seeing these error messages, even though I use latest 0d3b321 which is supposed to have fixed this.

`[2023-05-06 10:16:36.755] inf session.cc:644 Transmission version 4.1.0-dev (0d3b321bac) starting (session.cc:644)`
[...]
`[2023-05-06 10:46:34.754] inf global-ip-cache.cc:304 Successfully updated source IPv4 address to 192.168.178.22 (global-ip-cache.cc:304)`
`[2023-05-06 11:11:18.755] WRN tr-udp.cc:274 Couldn't send to [fd00::1]:55542: 101 (Network is unreachable) (tr-udp.cc:274)`
[...]
`[2023-05-06 11:16:01.754] WRN tr-udp.cc:274 Too many messages like this! I won't log this message anymore this session. (tr-udp.cc:274)`

**Comment by fredo-47** [comment]
@ckerr This issue is not fixed. It still occurs for me, even on the very latest built c61d8b7cf7.
I don't think this issues should be closed.

`[2023-05-09 18:30:35.534] WRN tr-udp.cc:274 Couldn't send to [fdd5:4d62:b83a:1:bd7e:4ac5:7409:fa7c]:11105: 101 (Network is unreachable) (tr-udp.cc:274)`
[...]
`[2023-05-09 18:51:56.534] WRN tr-udp.cc:274 Couldn't send to [fd03:1337::235]:41262: 101 (Network is unreachable) (tr-udp.cc:274)`
[...]
`[2023-05-09 18:57:34.533] inf global-ip-cache.cc:304 Successfully updated source IPv4 address to 192.168.178.22 (global-ip-cache.cc:304)`
[...]
`[2023-05-09 19:32:05.534] WRN tr-udp.cc:274 Couldn't send to [fd00::1]:37002: 101 (Network is unreachable) (tr-udp.cc:274)`
[...]
`[2023-05-09 19:32:42.533] WRN tr-udp.cc:274 Too many messages like this! I won't log this message anymore this session. (tr-udp.cc:274)`

**Comment by tearfur** [comment]
@fredo-47 At least it looks like all the warnings for global IPv6 addresses are gone, all of the messages you have are for unique local addresses.

What are these addresses? It would be helpful to know what is your network configuration as well.

**Comment by fredo-47** [comment]
@tearfur What do you need to know? If you tell me, I am totally willing to help.
As for my network configuration, I tried again https://test-ipv6.com/ , as requested by ckerr on January 19, and it is still the same result.

I don't know what the these addresses are.
Also suspecting they are peers, I tried to identify the torrent the related to.
I managed to find one of the torrents that produced this error message.  
Then with stopped daemon, I edited the resume file and deleted and ip6-peers from it. When I restarted the daemon, and that torrent connected to the tracker, it seems it got these addresses again from the tracker and also produced these error messages again.

I think, of course Transmission receives IP6 addresses of other peers from the tracker. 
However with an IP4-only network configuration, as mine, it should not try to connect to them, should it?

**Comment by tearfur** [comment]
These are private addresses, not addresses in the public internet. If these addresses are given by the tracker, and the tracker is not within your local network, then it is the tracker giving you bogus addresses to connect to. In other words, it is not Transmission's fault.

**Comment by fredo-47** [comment]
If I don't have IP6 network, then Transmission should not try to connect to IP6 addresses, no matter if these IP6 addresses are internal, public or bogus.

**Comment by tearfur** [comment]
We know you don't have IPv6 connectivity to the public internet from the test results of https://test-ipv6.com/.

However, you could be in a local network that *has* IPv6 connectivity. In that case, some additional peers can be discovered within the local network by LPD, without involvement from the tracker. Are you in such a network?

**Comment by fredo-47** [comment]
Thanks for your hint. I have looked deeper into this:

- In Transmission, LPD is not activated.
- In my DSL-router, IP6 is not activated.
- And in the network settings of my Linux Mint system, IP6 is deactivated, i.e. I do have only an internal IP4 address but no IP6 address (confirmed via `ifconfig` command
