### ISSUE TITLE
Transmission v4.0.1 crashes on startup when launching app

### ISSUE THREAD

**Issue by AWHubGit** [transmission/transmission#5077]
### What is the issue?

I had installed nightly build on macOS 13.2.1. macOS 13.2.1 has two user accounts. One account has not been used with Transmission. Second account has transmissions not finished by Transmission nightly build. Nightly build has been uninstalled and replaced by Transmission v4.0.1.

Transmission v.4.0.1 can be launched and is starting on account with no transmissions, but on account with unfinished transmissions app crashes on startup.

How to migrate from nightly build to v.4.0.1 reusing unfinished transmissions?

[crash_Transmission.pdf](https://github.com/transmission/transmission/files/10839908/crash_Transmission.pdf)

### Which application of Transmission?

macOS app

### Which version of Transmission?

v4.0.1

**Comment by ckerr** [comment]
```
Exception Type: EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes: 0x0000000000000001, 0x0000000000000000
Termination Reason: Namespace SIGNAL, Code 4 Illegal instruction: 4
Terminating Process: exc handler [14195]
Application Specific Backtrace 0:
0 CoreFoundation 0x00007ff818d693eb __exceptionPreprocess +
242
1 libobjc.A.dylib 0x00007ff8188b5e25 objc_exception_throw + 48
2 Foundation 0x00007ff819b57257 -[NSRLEArray init] + 0
3 Foundation 0x00007ff819b57007 -[NSConcreteAttributedString
initWithString:attributes:] + 27
4 Transmission 0x000000010b4ffe54 Transmission + 368212
5 Transmission 0x000000010b4fdf60 Transmission + 360288
6 AppKit 0x00007ff81c8b3a7c -[NSWrapperCellView drawRect:]
+ 581
7 AppKit 0x00007ff81bf8e194 _NSViewDrawRect + 121
8 AppKit 0x00007ff81c7733c3 -[NSView
_recursive:displayRectIgnoringOpacity:inContext:stopAtLayerBackedViews:] + 1810
9 AppKit 0x00007ff81c773711 -[NSView
_recursive:displayRectIgnoringOpacity:inContext:stopAtLayerBackedViews:] + 2656
10 AppKit 0x00007ff81c773711 -[NSView
_recursive:displayRectIgnoringOpacity:inContext:stopAtLayerBackedViews:] + 2656
11 AppKit 0x00007ff81bf8d8c0 -[NSView(NSLayerKitGlue)
_drawViewBackingLayer:inContext:drawingHandler:] + 753
12 AppKit 0x00007ff8
```

@mikedld where is Transmission 0x000000010b4ffe54 Transmission + 368212

**Comment by Coeur** [comment]
@ckerr it will depend on which nightly.
@AWHubGit please share the build number (from the nightly name).

**Comment by mikedld** [comment]
```
Transmission + 368212 -> -[TorrentCell attributedTitle]
Transmission + 360288 -> -[TorrentCell drawInteriorWithFrame:inView:]
```

**Comment by ckerr** [comment]
(@mikedld as an aside DYK if there's a newbie-friendly HOWTO that explains how to do this? I haven't done that on macOS before.)

**Comment by ckerr** [comment]
Anyone want to self-assign & triage this one, @Coeur @nevack @sweetppro ?

**Comment by Coeur** [comment]
`title` could only be nil if `representedObject` were nil, which I doubt it can happen. And the trace would be slightly different: it would more likely crash on `-[NSConcreteAttributedString initWithString:]` and not `-[NSRLEArray init]` (at least from me trying).
So I suspect more an issue with `fTitleAttributes`. I noticed that this property isn't present in the implementation of `copyWithZone:`, so maybe that's related?

**Comment by mikedld** [comment]
@ckerr, I'm using lldb and it's easy enough (not sure if there's an even easier way), but the Mac debug symbols we have released seem to contain a limited amount of info which sometimes makes the process a bit more complicated than it needs to be.

What I'm doing right now is:
* download release *.dmg and *-dbym.zip files
* extract Transmission.app and Transmission.app.dSYM into the same directory (alongside each other)
* start lldb, passing in architecture that's mentioned in the crash report, e.g. `lldb --arch x86_64 Transmission.app/Contents/MacOS/Transmission`
* lookup module base via `(lldb) target modules list` (Transmission is usually 0x0000000100000000, at least on my side)
* lookup symbols via `(lldb) source list -a 0x0000000100000000+368212` (base + offset from crash report)
* [optionally] try to guess the line numbers from `(lldb) disassemble -a 0x0000000100000000+368212` listing

Last step shouldn't be necessary but the next to last one doesn't seem to work as expected at all times: sometimes gives an error, sometimes prints just the filename but no line number.

**Comment by mikedld** [comment]
> > Transmission is usually 0x0000000100000000, at least on my side
> 
> OK, so getting this value is what `target modules list` is for, is that correct?

Yes. It's needed because base on user's machine is always different and so using absolute addresses from crash reports is impossible.

**Comment by ckerr** [comment]
@AWHubGit check out https://github.com/transmission/transmission/pull/5079#issuecomment-1446740947

**Comment by ckerr** [comment]
Possibly fixed by #5123; reopening pending confirmation from testers

**Comment by Coeur** [comment]
Note: and if still crashing, an updated crash log would be ideal. Thanks

**Comment by ckerr** [comment]
@AWHubGit ping ^

**Comment by AWHubGit** [comment]
I am sorry. I can't investigate further. I am not a coder nor a developer. I'll try transmission (again) when a new release for macOS is out.

**Comment by ckerr** [comment]
> lookup symbols via (lldb) source list -a 0x0000000100000000+368212 (base + offset from crash report)
>
> [optionally] try to guess the line numbers from (lldb) disassemble -a 0x0000000100000000+368212 listing

@mikedld when I tried this, the result was `error: 'source list' doesn't take any arguments.`

**Comment by mikedld** [comment]
@ckerr make sure there're no spaces in the address value, or that it's quoted otherwise, so that it's a single solid argument following `-a`.
