### ISSUE TITLE
Turtle/speed limit mode enabled on quit, but not enforced on client (re)start

### ISSUE THREAD

**Issue by nemws1** [transmission/transmission#5488]
### What is the issue?

Enabling the 'turtle' or speed limit mode works just fine, but if I quit the client with it enabled and then re-launch it, the "turtle" icon is shown as active, but the speed limits are set to the Global bandwidth limits, not the Speed Limit mode settings.

Disabling/re-enabling turtle (two clicks) fixes the issue after launch, but the speed limit should be enforced on launch.

In this screenshot, which is shortly after I started the client with turtle enabled *before* I quit, you can see speed limit mode is enabled (lower-left), but bandwidth used (upper middle) is exceeding Speed Limit mode rates (lower right).

![ss-20230502-173720](https://user-images.githubusercontent.com/9643802/235800801-39c34b55-fcd1-4fb1-a9f0-f036f436e851.png)

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.0.3

**Comment by Rodeo314** [comment]
I guess I experience this as well. I just through turtle wasn't working at all since 4.x, but it looks like disabling then re-enabling does seem to work for the most part (albeit rather more loosely than in 3.x, perhaps).

**Comment by nemws1** [comment]
Just noting... bug is still present in version 4.0.4 (24077e3511)

**Comment by 136785git** [comment]
Also experincing this bug in 4.0.4 on macOS

**Comment by bmrs** [comment]
This bug is still present in 4.0.5, and the off/on trick even does not work anymore… Thanks for handling this painful issue, especially when the bandwidth is limited!

**Comment by tearfur** [comment]
I think this is already fixed in the latest dev version. See #6736 for details.

**Comment by SNBogdanov** [comment]
No. It is not fixed on 4.0.6
In turtle mode new torrent starts in unlimited mode. Switch on/Switch off turtle mode put download into correct speed limit mode.
