### ISSUE TITLE
Contextual menus missing / don't work

### ISSUE THREAD

**Issue by ilikepeaches** [transmission/transmission#7299]
### What is the issue?

When the user ctrl-clicks / two-finger-taps / right-clicks on a torrent in the main window, a contextual menu should appear.  That menu looks like this:

<img width="245" alt="contextual-menu" src="https://github.com/user-attachments/assets/aa7eab60-0709-4b6d-94c7-ca238873a343" />

In 4.1.0-b1 on macOS, performing one of the above actions results in ... nothing.  There's no contextual menu, and nothing happens.

### Which application of Transmission?

macOS app

### Which version of Transmission?

4.1.0-beta.1 (c3a8106)

**Comment by hughlilly** [comment]
Can’t replicate on 4.1.0-beta.1 (c3a8106077), macOS 12.7.6 (21H1320).

**Comment by livings124** [comment]
I also can't seem to replicate on macOS 15.2

**Comment by TallestSkil** [comment]
I can confirm a reproduction. Like, I’m doing it right now. Not sure how I can present the evidence to you guys.

15.2 (24C101) with Transmission 4.1.0-beta.1 (c3a8106077). I was losing my mind until I realized it wasn’t my Magic Trackpad’s fault, mouse’s fault, or OS’s fault. It didn’t happen on 4.0.6, that’s for damned sure.

**Comment by Viktor45** [comment]
15.2 (24C101) 
4.1.0-beta.1 (c3a8106077)
to reproduce

full view: contextual menu works for icon and filename
compact view: contextual menu works for file icon only

**Comment by livings124** [comment]
This should be fixed with https://github.com/transmission/transmission/pull/7350

**Comment by dlite-hub** [comment]
This issue is back on version 4.1 for Mac OS, at least on Sequoia 15.7.3 (24G419). No contextual menu on right click, secondary click, etc. Both compact and expanded view.

**Comment by ilikepeaches** [comment]
> This issue is back on version 4.1 for Mac OS, at least on Sequoia 15.7.3 (24G419). No contextual menu on right click, secondary click, etc. Both compact and expanded view.

I can't reproduce, 4.1.0 release, 15.7.3 (24G419), Intel — the contextual menu works fine with my usual two-finger tap.  Compact view scroll performance and on-hover changes, on the other hand, are really slow and ugly, but that's a separate issue.
