### ISSUE TITLE
Bad formed json response

### ISSUE THREAD

**Issue by SNBogdanov** [transmission/transmission#8007]
### What is the issue?

I get new version from git 4.1.0. beta 4 and compiled it. But my application refuses to handle json reponces due to incorrect json. 
if i try to get json from transmission-remote it is absolutely correct, but if i try to check from response it missed value for tag
`{"arguments":{"alt-speed-down":2048,"alt-speed-enabled":false,"alt-speed-time-begin":390,"alt-speed-time-day":127,"alt-speed-time-enabled":false,"alt-speed-time-end":1320,"alt-speed-up":1024,"anti-brute-force-enabled":false,"anti-brute-force-threshold":100,"blocklist-enabled":false,"blocklist-size":0,"blocklist-url":"http://www.example.com/blocklist","cache-size-mb":2,"config-dir":"/var/lib/transmission-daemon/info","default-trackers":"","dht-enabled":true,"download-dir":"/share/Video/Incomplete","download-dir-free-space":1520493527040,"download-queue-enabled":true,"download-queue-size":20,"encryption":"tolerated","idle-seeding-limit":300,"idle-seeding-limit-enabled":true,"incomplete-dir":"/share/Data/Incomplete","incomplete-dir-enabled":true,"lpd-enabled":true,"peer-limit-global":1000,"peer-limit-per-torrent":20,"peer-port":54263,"peer-port-random-on-start":true,"pex-enabled":true,"port-forwarding-enabled":true,"preferred_transports":["utp","tcp"],"queue-stalled-enabled":true,"queue-stalled-minutes":1,"rename-partial-files":true,"reqq":2000,"rpc-version":18,"rpc-version-minimum":14,"rpc-version-semver":"6.0.0","script-torrent-added-enabled":false,"script-torrent-added-filename":"","script-torrent-done-enabled":true,"script-torrent-done-filename":"/share/Video/make_mkv.sh","script-torrent-done-seeding-enabled":false,"script-torrent-done-seeding-filename":"","seed-queue-enabled":true,"seed-queue-size":100,"seedRatioLimit":50.0,"seedRatioLimited":false,"sequential_download":true,"session-id":"5hAtbvMNv9xSNSH6GQ6xbpEnC07qkgWVlegPlwA1rdjaPiOy","speed-limit-down":5120.0,"speed-limit-down-enabled":true,"speed-limit-up":3072.0,"speed-limit-up-enabled":false,"start-added-torrents":true,"tcp-enabled":true,"trash-original-torrent-files":true,"units":{"memory-bytes":1024,"memory-units":["B","KiB","MiB","GiB","TiB"],"size-bytes":1000,"size-units":["B","kB","MB","GB","TB"],"speed-bytes":1000,"speed-units":["B/s","kB/s","MB/s","GB/s","TB/s"]},"utp-enabled":true,"version":"4.1.0-beta.4.dev (5602bcc74b)"},"result":"success","tag"}`

when I tried to get this into PHP json, or FPC json all failed due to incomplete string. When I manually add at the end "tag":"0" as it is displayed in transmission-remote json is parsed correctly

### Which application of Transmission?

transmission-daemon

### Which version of Transmission?

4.1.0.beta 4

**Comment by SNBogdanov** [comment]
It looks like this problem is caused by missing tag in request. After adding tag=0 I received it back. But tag is optional and it should not behave such way.

**Comment by ckerr** [comment]
This is very likely fixed by all the work being done at https://github.com/transmission/transmission/issues/7891#issuecomment-3635136911. 

If possible, could you test with a build from `main` and report back if there are any further issues?

*edit:* including the request payload + the expected and actual response payloads?

**Comment by reardonia** [comment]
> This is very likely fixed by all the work being done at [#7891 (comment)](https://github.com/transmission/transmission/issues/7891#issuecomment-3635136911).
> 
> If possible, could you test with a build from `main` and report back if there are any further issues?

It's still a problem with a1184061.  basically an empty "tag" is supplied in response to no "tag" being specified on (legacy) request.

The behavior is odd: for legacy RPC, the "id" key is now allowed an is synonymous with "tag".
```
{"method":"session-get","id":99}
```

Now responds with
```
{
   "arguments" : {...}
   "result" : "success",
   "tag" : 99
}
```

Further, a jsonrpc 2.0 request without "id" just does ... nothing.  No error.

Lastly: the jsonrpc spec seems to say that "id" is required but the new implementation doesn't require it and just silently fails.

**Comment by ckerr** [comment]
@tearfur do you have time to look into this? I'm going to be AFK for most of this next week. I'll be able to check in on my phone and push GitHub buttons but probably won't be doing triage / coding

**Comment by ckerr** [comment]
> It's still a problem with https://github.com/transmission/transmission/commit/a1184061a026dbad7d0d99c464a662bb2f91c155. basically an empty "tag" is supplied in response to no "tag" being specified on (legacy) request.

Do you mean the the below example of providing `"id"` instead of `"tag"`? Or do you mean something else? If the latter, please paste the request payload with the expected & actual response 👍 
 
> The behavior is odd: for legacy RPC, the "id" key is now allowed an is synonymous with "tag".
> 
> ```
> {"method":"session-get","id":99}
> ```
> 
> Now responds with
> 
> ```
> {
>    "arguments" : {...}
>    "result" : "success",
>    "tag" : 99
> }

This is a side-effect of the way the legacy <-> JSON-RPC conversion code works. In practice this shouldn't be an issue since legacy code won't be sending `"id"`?

> Further, a jsonrpc 2.0 request without "id" just does ... nothing. No error.
>
> Lastly: the jsonrpc spec seems to say that "id" is required but the new implementation doesn't require it and just silently fails.

@reardonia This may be a misreading of the spec? 

> A Notification is a Request object without an "id" member. A Request object that is a Notification signifies the Client's lack of interest in the corresponding Response object, and as such no Response object needs to be returned to the client. The Server MUST NOT reply to a Notification, including those that are within a batch request.

Though @tearfur the phrasing "MUST NOT reply to a notificaiton" implies that https://github.com/transmission/transmission/pull/7986#discussion_r2642257837 might be a bug?

**Comment by reardonia** [comment]
> This is a side-effect of the way the legacy <-> JSON-RPC conversion code works. In practice this shouldn't be an issue since legacy code won't be sending `"id"`?
> 
> > Further, a jsonrpc 2.0 request without "id" just does ... nothing. No error.
> > Lastly: the jsonrpc spec seems to say that "id" is required but the new implementation doesn't require it and just silently fails.
> 
> [@reardonia](https://github.com/reardonia) This may be a misreading of the spec?
> 
> > A Notification is a Request object without an "id" member. A Request object that is a Notification signifies the Client's lack of interest in the corresponding Response object, and as such no Response object needs to be returned to the client. The Server MUST NOT reply to a Notification, including those that are within a batch request.
> 
> Though [@tearfur](https://github.com/tearfur) the phrasing "MUST NOT reply to a notificaiton" implies that [#7986 (comment)](https://github.com/transmission/transmission/pull/7986#discussion_r2642257837) might be a bug?

Actually this seems proper, there is no response if "id" is missing.

The extraneous "tag" bug is still a problem but maybe the rest of this issue should be folded into #8005 , to decide how rigorous the error handling in the new jsonrpc should be?

**Comment by reardonia** [comment]
Maybe something like this in `api_compat::convert_jsonrpc()`

```
    if (is_jsonrpc)
    {
        top.try_emplace(TR_KEY_jsonrpc, tr_variant::unmanaged_string(JsonRpc::Version));
        if (auto const tag = top.value_if<int64_t>(TR_KEY_tag); state.was_legacy && !tag)
        {
            top.erase(TR_KEY_tag);
        }
        top.replace_key(TR_KEY_tag, TR_KEY_id);
    }
    else
    {
        top.erase(TR_KEY_jsonrpc);
        if (auto const tag = top.value_if<int64_t>(TR_KEY_id); state.was_jsonrpc && !tag)
            top.erase(TR_KEY_id);
        top.replace_key(TR_KEY_id, TR_KEY_tag);
    }
```

**Comment by tearfur** [comment]
> Though [@tearfur](https://github.com/tearfur) the phrasing "MUST NOT reply to a notificaiton" implies that [#7986 (comment)](https://github.com/transmission/transmission/pull/7986#discussion_r2642257837) might be a bug?

@ckerr This is not a bug. We are using JSON-RPC on top of the HTTP protocol, but HTTP is not part of JSON-RPC, so we are not sending any response within the scope of JSON-RPC. You can think of the HTTP 204 response like an ACK packet in TCP that has no payload.

**Comment by tearfur** [comment]
This whole bug report is weird.

The RPC response posted by @SNBogdanov shows that the daemon is running 5602bcc74b, which is *after* we've converted transmission-remote to use JSON-RPC, but the RPC response posted is in the old bespoke format. So maybe the request was sent using an older version of transmission-remote...?

Anyway, I tried running `transmission-remote -j -si` on 4.0.6 transmission-remote to 64f9c512dafc496949b1d471de4ea7b84fbe67e7 daemon, and I cannot reproduce the malformed response.

**Comment by SNBogdanov** [comment]
My request was formed not by transmission-remote, but php libraray. I also have free pascal application Transmission Remote GUI which also use OLD rpc.
Since you stated that old RPC should work even if it will be abandoned in future I use my application to run for beta daemons.
I have several daemons on my site, one was built roughly a week ago, and one was built yesterday with fresh code.
Problem is on fresh daemon.
I was able to fix problem with adding tag:0 to request, but this is not good solution since there are lot of old working application which are using old rpc scheme and these application just can not be updated.
I attached log from session info and torrent-get

[1.log](https://github.com/user-attachments/files/24343329/1.log)

**Comment by tearfur** [comment]
Ok, then I understand what's going on now.

* * *

@reardonia Would you like to raise a PR for your suggested solution at https://github.com/transmission/transmission/issues/8007#issuecomment-3691869138? I have review comments, but I'll wait for your PR to discuss them.

**Comment by SNBogdanov** [comment]
Also thery strange behaviour. For some clients request for torrent inf returned download-dir value instead of downloadDir
PS:
It looks like problem in  [[nodiscard]] tr_quark constexpr convert_key(State const& state, tr_quark const src)

**Comment by tearfur** [comment]
This is separate problem. Fix at #8015.

**Comment by SNBogdanov** [comment]
I manually added code from 8015 and solution, propsed by @reardonia in this issue and check th result. Everything is back to normal. I'm waiting to see it in main.

**Comment by ckerr** [comment]
This ticket hard to follow: it feels like there are a few different conversations going on. 

With 8015 landed + clearing up my confusion on the 204 reply + clearing up Reardonia's confusion on the optional id tag... it looks like everything is resolved except for the topic of how strict to be with requests that have invalid tags?

If so, let's close this ticket as fixed by 8015 and track strictness in a new issue.

**Comment by reardonia** [comment]
> This ticket hard to follow: it feels like there are a few different conversations going on.
> 
> With 8015 landed + clearing up my confusion on the 204 reply + clearing up Reardonia's confusion on the optional id tag... it looks like everything is resolved except for the topic of how strict to be with requests that have invalid tags?
> 
> If so, let's close this ticket as fixed by 8015 and track strictness in a new issue.

Apologies for making more confusing than it needed to be.  Agree that we should track jsonrpc strictness elsewhere (#8005)

The extraneous "tag" field is still just broken and causes json parsers to fail. @tearfur, for these (almost) one-line fixes for recent updates I thought it's best to just leave with the original author, so please feel free to take over from here. I'm away from main workstation and can't easily generate PR anyway.

**Comment by ckerr** [comment]
Ok you're referring to the 'tag' in this snippet, correct?

> ,"result":"success","tag"}

I.e. a JSON object property without a value?

**Comment by reardonia** [comment]
> Ok you're referring to the 'tag' in this snippet, correct?
> 
> > ,"result":"success","tag"}
> 
> I.e. a JSON object property without a value?

Yes
